[Core] Read rerun files from directories
cucumber/cucumber-jvm pull request #2710
Opened 2023-03-20 20:42 UTC by dbfwhitney

Added a method to try and add functionality to process all rerun folders in a directory (if more than 0 files exist). Still needs work as not sure how to implement walkFileTree method.

2023-03-23 19:20 UTC, mpkorstanje requested changes
Looks good! Now there are a few more things that need to be done before this can be merged.

1. Write some tests.
2. Clean up the code
3. Update the `CHANGELOG.md`

Once that is done the feature can be released.

## Writing tests

The test for this class would go into the `CucumberPropertiesParserTest`. There already is a test for `should_parse_rerun_file` so you can use that to pattern a few more tests. I reckon the important cases are a directory with no files and a directory with two files.

These tests will make the next part easier.

## Cleaning up the code

I've left some comments on the code itself. They'll make the code a bit better.

## Update the CHANGELOG

In the `CHANGELOG.md` file you can add a `### Fixed` header and add an entry for your change. Have a look at the older entries to see the format used.

2023-03-23 19:20 UTC, mpkorstanje commented on cucumber-core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java
> +    private static Set<String> listRerunFiles(String path) {
Consider returning a `Set<Path>` instead. The file visitor already provides you with `Path`s and the `parseFeatureWithLinesFile` also consumes paths.

2023-03-23 19:20 UTC, mpkorstanje commented on cucumber-core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java
> +                        fileList.add(path + "/" + file.getFileName().toString());
If I'm not mistaken, the `Path file` is a complete path the the rerun file. So you can directly add it to the the `fileList`.

2023-03-23 19:20 UTC, mpkorstanje commented on cucumber-core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java
> +    private static Set<String> listRerunFiles(String path) {
And to make reading this code a bit easier, putting this method after `parseRerunFiles` would be nice.

2023-04-05 16:50 UTC, mpkorstanje commented
Pushed some changes. Still have to update the docs on `@CucumberOptions`, `USAGE.txt`, `Constants.java`, ect.

2023-04-13 12:31 UTC, mpkorstanje approved these changes

2023-04-13 12:40 UTC, merged

2023-04-13 12:40 UTC, aslakhellesoy commented
Hi @dbfwhitney,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

2023-04-13 12:42 UTC, mpkorstanje commented
@dbfwhitney thanks for the first setup.