Fixed test failure by comparing maps instead of json strings
cucumber/cucumber-jvm pull request #2822
Opened 2023-11-29 21:59 UTC by RugvedB

### ⚡️ What's your motivation? 

Created this PR to fix 1 flaky test - [test](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/test/java/io/cucumber/core/plugin/MessageFormatterTest.java#L22).

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----
### Further Details:
1. **How were these test identified as flaky?**
This test was identified as flaky by using an open-source research tool named [NonDex](https://github.com/TestingResearchIllinois/NonDex) which is responsible for finding and diagnosing non-deterministic runtime exceptions in Java programs.

2. **What was the error?**
When the test convert bytes to json string `String ndjson = new String(bytes.toByteArray(), UTF_8);`, the order of keys (i.e. seconds, nano, testRunStarted, testRunFinished, etc) is not guaranteed. Thus, when we compare this String variable 'ndjson' directly to hardcoded string `"{\"testRunStarted\":{\"timestamp\":{\"seconds\":10,\"nanos\":0}}}\n{\"testRunFinished\":{\"success\":true,\"timestamp\":{\"seconds\":15,\"nanos\":0}}}\n"`, it may fail sometimes because the order could be different than the expected order.
```
[ERROR] Failures: 
[ERROR]   MessageFormatterTest.test:35 
Expected: a string containing "{\"testRunStarted\":{\"timestamp\":{\"seconds\":10,\"nanos\":0}}}\n{\"testRunFinished\":{\"success\":true,\"timestamp\":{\"seconds\":15,\"nanos\":0}}}\n"
     but: was "{"testRunStarted":{"timestamp":{"nanos":0,"seconds":10}}}
{"testRunFinished":{"timestamp":{"nanos":0,"seconds":15},"success":true}}
"
```
3. **What is the fix?**
```
assertThat(expectedMap.entrySet(), everyItem(is(in(ndjsonMap.entrySet()))));
```
Instead of comparing json strings, we can convert json to Map and then compare the maps. This PR proposes to compare Maps instead of json strings in test. In the above code snippet, the assertion checks that every entry in expectedMap is present in ndjsonMap. If this assertion passes for every entry in expectedMap, it means that the key-value pairs in expectedMap are all present in ndjsonMap.

--------------
You can run the following commands to run the test using NonDex tool:
```
mvn -pl cucumber-core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=io.cucumber.core.plugin.MessageFormatterTest#test
```

Test Environment:
```
java version 11.0.19
Apache Maven 3.9.5
```
Kindly let me know if this fix is acceptable.
Thank you

2023-12-01 16:55 UTC, mpkorstanje requested changes
Hi, thanks for discovering and offering to fix this.

The suggested fix is more complicated than needed and also incorrect. 

As a general pointer I would suggest declaring the expected ndjson as an array of strings, and splitting the actual ndjson into an array of strings. You can then compare the elements of this array using `JSONAssert.assertEquals`.

Unfortunately I do not have more time available to coach you on a better solution.

2023-12-01 16:55 UTC, mpkorstanje commented on cucumber-core/src/test/java/io/cucumber/core/plugin/MessageFormatterTest.java
> +        String expectedJson = "{\"testRunStarted\":{\"timestamp\":{\"seconds\":10,\"nanos\":0}},\"testRunFinished\":{\"success\":true,\"timestamp\":{\"seconds\":15,\"nanos\":0}}}";
This meaningfully changes what is being tested. Json and Ndjson are distinctly different. See https://ndjson.org/

2023-12-01 16:55 UTC, mpkorstanje commented on cucumber-core/src/test/java/io/cucumber/core/plugin/MessageFormatterTest.java
> +            assertThat(expectedMap.entrySet(), everyItem(is(in(ndjsonMap.entrySet()))));
Have you considered using `JSONAssert.assertEquals`?

2023-12-01 20:45 UTC, mpkorstanje commented
That looks reasonable but please provide your suggestions as a commit. Note that to improve readability you can use shortcut syntax to create and initialize an array for the expected ndjson. 

https://docs.oracle.com/javase/tutorial/java/nutsandbolts/arrays.html

2023-12-01 21:11 UTC, RugvedB commented
> That looks reasonable but please provide your suggestions as a commit. Note that to improve readability you can use shortcut syntax to create and initialize an array for the expected ndjson.
> 
> https://docs.oracle.com/javase/tutorial/java/nutsandbolts/arrays.html

@mpkorstanje Thanks you for your guidance. I have pushed the changes. Feel free to let me know if further steps need to be taken to make it perfect. Also, let me know if you want me to squash the commits into 1 commit. Thanks for your time.

2023-12-03 17:00 UTC, mpkorstanje approved these changes
Cheers! This looks good. I've pushed a few cosmetic changes on your branch. 

It's not necessary to to put the name of the type into a variable. The type is right in front of it. Also I used static imports to keep the code a bit more succinct.

Squashing won't be necessary. It's the default mode for merging in this Git repo.

2023-12-03 17:03 UTC, merged